---
safe        : true
lsi         : false
permalink   : none
markdown    : kramdown

title:            'Saeed Abdullah'
tagline:          ''
description:      'Assistant Professor, Penn State IST. <a href="https://twitter.com/saeed_siam">@saeed_siam</a>'
url:              saeedabdullah.com

author:
  name:           'Saeed Abdullah'
  url:            https://twitter.com/saeed_siam

# paginate:         5

theme: jekyll-theme-cayman