---
auto        : false
lsi         : false
pygments    : true
permalink   : none
markdown    : maruku

maruku:
    use_divs: false
    use_tex: false
    png_engine : blahtex
    png_dir    : images/latex/
    png_url    : /images/latex/

    
