---
safe        : true
lsi         : false
permalink   : none
markdown    : kramdown

title:            'Saeed Abdullah'
description:      'Personal webpage of Saeed Abdullah (assistant professor, Penn State).'
url:              saeedabdullah.com

author:
  name:           'Saeed Abdullah'

exclude:
  - Makefile
  - sanitizers/

# paginate:         5
